server:
  port: 8002 #订单服务端口号
spring:
  application:
    name: app-xrz-order #服务别名  服务注册到注册中心名称
eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8100/eureka #当前服务注册到eureka服务地址 （服务中心的地址）
    register-with-eureka: true #需要将我的服务注册到eureka上
    fetch-registry: true #需要检索服务
#设置feign客户端超时时间
ribbon: #springCloud feign客户端默认开启支持ribbon(本地均衡负载器)
  ReadTimeout: 5000 #指的是建立链接所用时间，适用于网络情况正常的情况下，两端链接所用的时间（5s）
  ConnectTimeout: 5000 #指的是建立链接后从服务器读取到可用资源所用的时间（5s）